server:
  servlet:
    context-path: "/grandchild-svc"
  port: 5050

spring:
  application:
    name: "Grandchild"
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus


  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
